---
- name: "Ensure GPG tool is installed."
  apt: name="gpgv" state="present"

- name: "Add repository."
  template:
    src: templates/source-java.list.j2
    dest: /etc/apt/sources.list.d/linuxuprising-java.list

- name: "Add repo key."
  apt_key:
    keyserver: "{{ java_key_server }}"
    id: "{{ java_key }}"
